FROM docker.io/oven/bun:latest

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN bun install
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    netcat \
    iputils-ping && \
    rm -rf /var/lib/apt/lists/*

# Copy the rest of the application
COPY . .

# Expose port
EXPOSE 3000
